### ISSUE TITLE
map sound inventory sizes

### ISSUE THREAD

**Issue by LinguList** [lexibank/abvdoceanic#11]
- [x] extract a structure dataset with inventory size on sounds
- [x] map to show the distribution

**Comment by LinguList** [comment]
The file can be found now [here](https://github.com/lexibank/abvdoceanic/blob/main/plots/map.pdf). @antipodite, in the file `workflow.md` there are instructions how to create this plot. You could also test other features, like wordlength, and the like.

**Comment by antipodite** [comment]
Awesome, I'll spend tomorrow playing around with this and the various packages.

I actually tried out generating an orthography profile on the ACD this arvo. Didn't work too well but I think with some cleaning of the data in my fork it could be made to work. Just experimenting for learning purposes

-------- Original Message --------

**Comment by LinguList** [comment]
If you make an orthoprofile the first time with lingpy / pylexibank,it is very useful to see how many lines it has: if you do not merge vowels (which is increasing lines in AN data) and do not use the context function, and get some 1000 lines, it is feasible. If you get 3000 lines, you should do some cleaning to the forms.

**Comment by LinguList** [comment]
I can check this also later today.

**Comment by LinguList** [comment]
@antipodite, if the mapping thing works, using my instructions, you can close this issue.

**Comment by antipodite** [comment]
All working. I needed to explicitly install cltoolkit for `cldfbench abvdoceanic.structure lexibank_abvdoceanic.py` to work, should this be in the pkg requirements somewhere?

**Comment by LinguList** [comment]
Yes, perfect, could you add it?
