### ISSUE TITLE
[Orthography] Ulithian: many duplicate forms from two different sources

### ISSUE THREAD

**Issue by LinguList** [lexibank/abvdoceanic#16]
![Screenshot 2021-08-25 at 13-51-26 EDICTOR](https://user-images.githubusercontent.com/2916210/130785453-688cb629-49a6-4065-a6e6-dd6fa6b8df80.png)

**Comment by LinguList** [comment]
The problem of this outlier in the data (45 consonants!) is that it seems to have been composed of two different sources using two different alphabets. It seems this can only be manually resolved.

**Comment by LinguList** [comment]
Should we exclude it for now from the data?

**Comment by maryewal** [comment]
Do we have two separate lists for it or are these sources combined into one set?

**Comment by LinguList** [comment]
Ah, @antipodite, in order to get this rolling, can you now post the words to REMOVE to a file `etc/ignore.tsv`, where you give me three values, as discussed before, e.g., for a form `paththba` (which I just invented)

Language_ID | Parameter_Name | Value | Comment
--- | --- | --- | --- 
Ulithian | hand | gumchiu | duplicate

This TSV file would then serve as the basis to exclude entries from being listed as "normal" entries.

**Comment by antipodite** [comment]
Done, check pull requests

**Comment by antipodite** [comment]
want me to have a go at plumbing in `ignore.tsv`? Seems like you would just filter against `ignore.tsv` in the `def cmd_makecldf(self, args):` fn definition in `lexibank_abvdoceanic.py`

**Comment by maryewal** [comment]
@antipodite, based on what you say, it seems sensible to remove the pronunciation guide forms. Do you still want me to have a look at this?

**Comment by LinguList** [comment]
So we insert an if-else check before this line:

https://github.com/lexibank/abvdoceanic/blob/8fb24c8d9c455e4e2e502b0b2bfe8154941463d8/lexibank_abvdoceanic.py#L105-L117

@antipodite, before this line, you can check for same value, language ID and concept id:

```python
lid = slug(wl.language.name, lowercase=False)
if ignored.get(lid, cid, entry.name):
    continue
```

Before, e.g., right after `def cmd_makecldf` you load the ignored list:

```python
ignored = {(row[0], row[1], row[2]): row[3] for row in self.etc_dir.read_csv("ignore.tsv", delimiter="\t")}
```

You have to play a round with this, as I did not test, but along those lines, it should work, and I gladly review this, if you make another PR and assign me as a reviewer.

**Comment by antipodite** [comment]
@maryewal I think we should just go ahead with removing the guide forms. No need to look at it again. @mattis cool, I'll have a look some time tomorrow

**Comment by maryewal** [comment]
Can we close this?

**Comment by antipodite** [comment]
yup, we sorted this iirc
