### ISSUE TITLE
[Orthography] Check NititaKhatbol profile

### ISSUE THREAD

**Issue by LinguList** [lexibank/abvdoceanic#18]
There are cases like saxᵐbuɣut -> s a xⁿ b u ɣ u t, so the segmentation is wrong here `xᵐb` should be `x ⁿb`.

**Comment by maryewal** [comment]
@LinguList so, in this case, would we simply delete the xⁿ segment from the profile?

Line 104: xᵐ	xⁿ	1

**Comment by LinguList** [comment]
Yes, this normally does the trick!
