### ISSUE TITLE
[Orthography] Marquesan has too many vowels and consonants

### ISSUE THREAD

**Issue by antipodite** [lexibank/abvdoceanic#19]
The problem here seems to be that the forms in the ABVD come from different sources which used different orthographies -- Dordillon's dictionary indicates long vowels with an acute accent but later Marquesan orthography doubles the vowel. We also have some extremely garbled forms that seem to be the result of poor transcription

**Comment by maryewal** [comment]
So, I have separated these out, but not sure what we should actually do here - unfortunately, the set isn't as straaight forward as each variety having the full list of concepts. By removing the South Mqsic (or North) we get significantly reduced coverage. If we keep both varieties together for a "Marquesan" language, we will get a full set of consonants. There are some additional consonants/vowels in there from Dordillon's old orthography (d = r, accented vowels, etc) that when corrected will reduce the overall number of consonants and will definitely correct the number of vowels. @SimonGreenhill @LinguList curious about your thoughts. My opinion is it is better to leave the varieties together (correcting the Dordillon orth, obviously) for max coverage.

**Comment by LinguList** [comment]
Yes, I think this is reasonable for now. As long as no hard-core historical comparison is involved, one can proceed by not splitting. If it was for the sound correspondences ultimately, one might be forced to manually reconstruct one variety from the information of the other. But for the current purposes, we won't need that level of rigor.
