### ISSUE TITLE
Check to which degree synonymy and mutual coverage influence the phylogenetic analysis

### ISSUE THREAD

**Issue by LinguList** [lexibank/abvdoceanic#27]
We have detected from #26 already that we have some cases of excess synonymy. It seems reasonable to repeat the [tossing-coins](http://phylonetworks.blogspot.com/2018/02/tossing-coins-linguistic-phylogenies.html) analysis to see how much this influences the phylogenies (albeit that this check only looks at NJ trees).

**Comment by LinguList** [comment]
A similar analysis can be done with mutual coverage then.

**Comment by SimonGreenhill** [comment]
Suspect NJ will struggle with these data...

**Comment by LinguList** [comment]
Agree, but there's no systematic study investigating how much this would affect Bayesian analyses, or is there? But as we discussed elsewhere, this is probably better done in another context with a dedicated and small dataset for testing, so one can run sufficient analyses.
