### ISSUE TITLE
Malekula transcriptions incorrect - correct by modifying per-language profiles

### ISSUE THREAD

**Issue by antipodite** [lexibank/abvdoceanic#30]
Making this issue cf. our email chain.

I just tested Timo's updated profile for Neverver (Lingarak - Sakan), copying changes into the source column and re-running `cldfbench lexibank.makecldf`. Now `cldfbench abvdoceanic.inventories` gives us 7 vowels and 21 consonants, down from 14 V and 34 C. Does this look correct? If so we can get started tomorrow on the rest of the profiles. Can't assign Timo is he on this repo?

**Comment by maryewal** [comment]
Thanks @antipodite. I think that is much more reasonable sounding! I also had toruble assigning and tagging Timo here. Perhaps he needs to be added as a collaborator @LinguList? His user name is @tihomirrangelov.

**Comment by tihomirrangelov** [comment]
7 vowels and 21 consonants is definitely much closer to the truth.

**Comment by antipodite** [comment]
Pushed all Timo's edited profiles into the master orthoprofile dir

**Comment by maryewal** [comment]
@tihomirrangelov and I discussed yesterday and he will go through the rest of these starting next week. He'll make the edits directly in the repo and flag any concerns/questions as issues [Orthography-Malekula].

**Comment by antipodite** [comment]
Cool, @tihomirrangelov make a branch so you can do the pull request:
```
cd abvdoceanic
git branch profiles
git checkout profiles
```
Then when you've `git push`ed your changes, go to [[https://github.com/lexibank/abvdoceanic/pulls]] and click "Create pull request".
