### ISSUE TITLE
Orthography Profiles Malekula

### ISSUE THREAD

**Issue by maryewal** [lexibank/abvdoceanic#47]
@antipodite should all of the updates that @tihomirrangelov made in https://github.com/lexibank/abvdoceanic/tree/main/etc/malekula also be reflected for the Malekula languages in the general orthography (https://github.com/lexibank/abvdoceanic/tree/main/etc/orthography) folder, or does it not matter?

**Comment by SimonGreenhill** [comment]
they should be consistent

**Comment by maryewal** [comment]
In cross-checking just a couple, it seems to me that they are not. At least some Malekula languages in the main orthography folder do not reflect Timo's changes in the malekula folder. I suspect this may be why we still are seeing discrepancies in Malekula language counts. Can @antipodite make sure the Malekula folder changes are all reflected in the main?

**Comment by LinguList** [comment]
@antipodite, did you run the command `cldfbench abvdoceanic.inventories` which counts the phonemes, rather than the command that creates the CLDF data?

**Comment by antipodite** [comment]
Yeah I did, should have specified I ran both, once each before moving the profiles, and then once each again after moving them

**Comment by LinguList** [comment]
Le us check the diffs then, if you updated the profiles? Could you have a look at them, and see what kinds of changes you have there?

**Comment by LinguList** [comment]
@antipodite, there is another issue. You swapped columns (at least in the first profile). The code reads colummn IPA, but you left IPA as is and called IPAInSource, where you edited, I think. This would explain why nothing happens. If you swap column names, using IPA for the new replacements, this should work, I hope.

**Comment by LinguList** [comment]
@antipodite, if you find this issue to be solved, you can close it.
